
// Sim value ids ===============================================================
// Aircraft position
#define SIM_FLIGHTMODEL_POSITION_GROUNDSPEED 0
#define SIM_FLIGHTMODEL_POSITION_TRUE_AIRSPEED 1
#define SIM_FLIGHTMODEL_POSITION_MAGPSI 2
#define SIM_FLIGHTMODEL_POSITION_HPATH 3
#define SIM_FLIGHTMODEL_POSITION_LATITUDE 4		// double!
#define SIM_FLIGHTMODEL_POSITION_LONGITUDE 5 	// double!
#define SIM_FLIGHTMODEL_POSITION_PHI 6 			// roll angle
#define SIM_FLIGHTMODEL_POSITION_R 7 			// rotation rate
#define SIM_FLIGHTMODEL_POSITION_MAGVAR 8
#define SIM_FLIGHTMODEL_POSITION_ELEVATION 9
#define SIM_FLIGHTMODEL_POSITION_Y_AGL 10

// Instruments
#define SIM_FLIGHTMODEL_POSITION_VH_IND_FPM 50	// new for 1.0 Beta 8
#define SIM_FLIGHTMODEL_MISC_H_IND 51			// new for 1.0 Beta 8

// Electrical
#define SIM_COCKPIT_ELECTRICAL_AVIONICS_ON 80
#define SIM_COCKPIT2_SWITCHES_AVIONICS_POWER_ON 81

// Radios
#define SIM_COCKPIT_RADIOS_NAV1_FREQ_HZ 100
#define SIM_COCKPIT_RADIOS_NAV2_FREQ_HZ 101
#define SIM_COCKPIT_RADIOS_ADF1_FREQ_HZ 102
#define SIM_COCKPIT_RADIOS_ADF2_FREQ_HZ 103
#define SIM_COCKPIT_RADIOS_NAV1_DIR_DEGT 104
#define SIM_COCKPIT_RADIOS_NAV2_DIR_DEGT 105
#define SIM_COCKPIT_RADIOS_ADF1_DIR_DEGT 106
#define SIM_COCKPIT_RADIOS_ADF2_DIR_DEGT 107
#define SIM_COCKPIT_RADIOS_NAV1_DME_DIST_M 108
#define SIM_COCKPIT_RADIOS_NAV2_DME_DIST_M 109
#define SIM_COCKPIT_RADIOS_ADF1_DME_DIST_M 110
#define SIM_COCKPIT_RADIOS_ADF2_DME_DIST_M 111
#define SIM_COCKPIT_RADIOS_NAV1_OBS_DEGM 112
#define SIM_COCKPIT_RADIOS_NAV2_OBS_DEGM 113
#define SIM_COCKPIT_RADIOS_NAV1_COURSE_DEGM 114
#define SIM_COCKPIT_RADIOS_NAV2_COURSE_DEGM 115
#define SIM_COCKPIT_RADIOS_NAV1_CDI 116
#define SIM_COCKPIT_RADIOS_NAV2_CDI 117
#define SIM_COCKPIT_RADIOS_NAV1_HDEF_DOT 118		// new for 1.0 Beta 8
#define SIM_COCKPIT_RADIOS_NAV2_HDEF_DOT 119	 	// new for 1.0 Beta 8
#define SIM_COCKPIT_RADIOS_NAV1_FROMTO 120 			// new for 1.0 Beta 8
#define SIM_COCKPIT_RADIOS_NAV2_FROMTO 121 			// new for 1.0 Beta 8
#define SIM_COCKPIT_RADIOS_NAV1_VDEF_DOT 122		// new for 1.0 Beta 8
#define SIM_COCKPIT_RADIOS_NAV2_VDEF_DOT 123	 	// new for 1.0 Beta 8

#define SIM_COCKPIT_RADIOS_GPS_DIR_DEGT 124			// new for 1.0 Beta 8
#define SIM_COCKPIT_RADIOS_GPS_DME_DIST_M 125	 	// new for 1.0 Beta 8
#define SIM_COCKPIT_RADIOS_GPS_COURSE_DEGTM 126		// new for 1.0 Beta 8
#define SIM_COCKPIT_RADIOS_GPS_HDEF_DOT 127 		// new for 1.0 Beta 8
#define SIM_COCKPIT_RADIOS_GPS_FROMTO 128 			// new for 1.0 Beta 8
#define SIM_COCKPIT_RADIOS_GPS_VDEF_DOT 129 		// new for 1.0 Beta 8

#define SIM_COCKPIT_RADIOS_NAV1_DME_TIME_SECS 130 	// new for 1.0 Beta 8
#define SIM_COCKPIT_RADIOS_NAV2_DME_TIME_SECS 131 	// new for 1.0 Beta 8
#define SIM_COCKPIT_RADIOS_GPS_DME_TIME_SECS 132 	// new for 1.0 Beta 8

#define SIM_COCKPIT2_RADIOS_INDICATORS_NAV1_NAV_ID 10140  // new for 1.0 Beta 16
#define SIM_COCKPIT2_RADIOS_INDICATORS_NAV2_NAV_ID 10141  // new for 1.0 Beta 16
#define SIM_COCKPIT2_RADIOS_INDICATORS_ADF1_NAV_ID 10142  // new for 1.0 Beta 16
#define SIM_COCKPIT2_RADIOS_INDICATORS_ADF2_NAV_ID 10143  // new for 1.0 Beta 16


// AP
#define SIM_COCKPIT_AUTOPILOT_STATE 150
#define SIM_COCKPIT_AUTOPILOT_VERTICAL_VELOCITY 151
#define SIM_COCKPIT_AUTOPILOT_ALTITUDE 152
#define SIM_COCKPIT_AUTOPILOT_APPROACH_SELECTOR 153
#define SIM_COCKPIT_AUTOPILOT_HEADING_MAG 154		// was 200 before Beta 9

// Transponder
#define SIM_COCKPIT_RADIOS_TRANSPONDER_MODE 180		// new for 1.0 Beta 11

// EFIS
#define SIM_COCKPIT_SWITCHES_HSI_SELECTOR 200	 	// new for 1.0 Beta 8
#define SIM_COCKPIT_SWITCHES_EFIS_MAP_RANGE_SELECTOR 201
#define SIM_COCKPIT_SWITCHES_EFIS_DME_1_SELECTOR 202
#define SIM_COCKPIT_SWITCHES_EFIS_DME_2_SELECTOR 203
#define SIM_COCKPIT_SWITCHES_EFIS_SHOWS_WEATHER 204
#define SIM_COCKPIT_SWITCHES_EFIS_SHOWS_TCAS 205
#define SIM_COCKPIT_SWITCHES_EFIS_SHOWS_AIRPORTS 206
#define SIM_COCKPIT_SWITCHES_EFIS_SHOWS_WAYPOINTS 207
#define SIM_COCKPIT_SWITCHES_EFIS_SHOWS_VORS 208
#define SIM_COCKPIT_SWITCHES_EFIS_SHOWS_NDBS 209
#define SIM_COCKPIT_SWITCHES_EFIS_MAP_MODE 210 		// new for 1.0 Beta 8
#define SIM_COCKPIT_SWITCHES_EFIS_MAP_SUBMODE 211 	// new for 1.0 Beta 8
#define XHSI_EFIS_PILOT_STA 212
#define XHSI_EFIS_PILOT_DATA 213
#define XHSI_EFIS_PILOT_POS 214

// Copilot EFIS
#define XHSI_EFIS_COPILOT_HSI_SOURCE 250
#define XHSI_EFIS_COPILOT_MAP_RANGE 251
#define XHSI_EFIS_COPILOT_RADIO1 252
#define XHSI_EFIS_COPILOT_RADIO2 253
#define XHSI_EFIS_COPILOT_WXR 254
#define XHSI_EFIS_COPILOT_TFC 255
#define XHSI_EFIS_COPILOT_ARPT 256
#define XHSI_EFIS_COPILOT_WPT 257
#define XHSI_EFIS_COPILOT_VOR 258
#define XHSI_EFIS_COPILOT_NDB 259
#define XHSI_EFIS_COPILOT_MAP_CTR 260
#define XHSI_EFIS_COPILOT_MAP_MODE 261
#define XHSI_EFIS_COPILOT_STA 262
#define XHSI_EFIS_COPILOT_DATA 263
#define XHSI_EFIS_COPILOT_POS 264

// Environment
#define SIM_WEATHER_WIND_SPEED_KT 300
#define SIM_WEATHER_WIND_DIRECTION_DEGT 301
#define SIM_TIME_ZULU_TIME_SEC 302
#define SIM_TIME_LOCAL_TIME_SEC 303

// Plugin Version
#define PLUGIN_VERSION_ID 400

